{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false,
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\u001b[00;36mbeep-01a.mp3\u001b[0m\r\n",
      "\u001b[00;36mbeep.mp3\u001b[0m\r\n",
      "gpu_testing.ipynb\r\n",
      "\u001b[01;34minitial_kaggle_download_zip_files\u001b[0m/\r\n",
      "\u001b[01;34minput\u001b[0m/\r\n",
      "LSTM with word2vec embeddings-backup_20171130.ipynb\r\n",
      "LSTM with word2vec embeddings-backup_at_error_point.ipynb\r\n",
      "LSTM with word2vec embeddings.ipynb\r\n",
      "LSTM with word2vec embeddings_setting_up_backup.ipynb\r\n",
      "LSTM with word2vec embeddings-setting_up.ipynb\r\n",
      "theano_test.py\r\n",
      "Untitled.ipynb\r\n"
     ]
    }
   ],
   "source": [
    "ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "!mkdir testing_keras"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/LSTM_Hew/testing_keras\n"
     ]
    }
   ],
   "source": [
    "cd testing_keras/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false,
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "import numpy\n",
    "# fix random seed for reproducibility\n",
    "numpy.random.seed(7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false,
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--2017-12-01 05:03:22--  http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data\n",
      "Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249\n",
      "Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:80... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 23279 (23K) [text/plain]\n",
      "Saving to: ‘pima-indians-diabetes.data’\n",
      "\n",
      "pima-indians-diabet 100%[===================>]  22.73K  --.-KB/s    in 0.03s   \n",
      "\n",
      "2017-12-01 05:03:22 (713 KB/s) - ‘pima-indians-diabetes.data’ saved [23279/23279]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!wget http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "!mv pima-indians-diabetes.data pima-indians-diabetes.csv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# load pima indians dataset\n",
    "dataset = numpy.loadtxt(\"pima-indians-diabetes.csv\", delimiter=\",\")\n",
    "# split into input (X) and output (Y) variables\n",
    "X = dataset[:,0:8]\n",
    "Y = dataset[:,8]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# create model\n",
    "model = Sequential()\n",
    "model.add(Dense(12, input_dim=8, activation='relu'))\n",
    "model.add(Dense(8, activation='relu'))\n",
    "model.add(Dense(1, activation='sigmoid'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Compile model\n",
    "model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO (theano.gof.compilelock): Refreshing lock /home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/lock_dir/lock\n",
      "1 #include <Python.h>\n",
      "2 #include <iostream>\n",
      "3 #include \"theano_mod_helper.h\"\n",
      "4 #include \"cuda_ndarray.cuh\"\n",
      "5 //////////////////////\n",
      "6 ////  Support Code\n",
      "7 //////////////////////\n",
      "8 \n",
      "9 \n",
      "10     namespace {\n",
      "11     struct __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e {\n",
      "12         PyObject* __ERROR;\n",
      "13 \n",
      "14         PyObject* storage_V3;\n",
      "15 PyObject* storage_V1;\n",
      "16         \n",
      "17 \n",
      "18         __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e() {\n",
      "19             // This is only somewhat safe because we:\n",
      "20             //  1) Are not a virtual class\n",
      "21             //  2) Do not use any virtual classes in the members\n",
      "22             //  3) Deal with mostly POD and pointers\n",
      "23 \n",
      "24             // If this changes, we would have to revise this, but for\n",
      "25             // now I am tired of chasing segfaults because\n",
      "26             // initialization code had an error and some pointer has\n",
      "27             // a junk value.\n",
      "28             memset(this, 0, sizeof(*this));\n",
      "29         }\n",
      "30         ~__struct_compiled_op_3a084fd032db206a67ca8121a24aa32e(void) {\n",
      "31             cleanup();\n",
      "32         }\n",
      "33 \n",
      "34         int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1) {\n",
      "35             Py_XINCREF(storage_V3);\n",
      "36 Py_XINCREF(storage_V1);\n",
      "37             this->storage_V3 = storage_V3;\n",
      "38 this->storage_V1 = storage_V1;\n",
      "39             \n",
      "40 \n",
      "41 \n",
      "42 \n",
      "43             this->__ERROR = __ERROR;\n",
      "44             return 0;\n",
      "45         }\n",
      "46         void cleanup(void) {\n",
      "47             __label_1:\n",
      "48 \n",
      "49 double __DUMMY_1;\n",
      "50 __label_3:\n",
      "51 \n",
      "52 double __DUMMY_3;\n",
      "53 __label_6:\n",
      "54 \n",
      "55 double __DUMMY_6;\n",
      "56 \n",
      "57             Py_XDECREF(this->storage_V3);\n",
      "58 Py_XDECREF(this->storage_V1);\n",
      "59         }\n",
      "60         int run(void) {\n",
      "61             int __failure = 0;\n",
      "62             \n",
      "63     PyObject* py_V1;\n",
      "64      CudaNdarray * V1;\n",
      "65     PyObject* py_V3;\n",
      "66      CudaNdarray * V3;\n",
      "67 {\n",
      "68 \n",
      "69     py_V1 = PyList_GET_ITEM(storage_V1, 0);\n",
      "70     {Py_XINCREF(py_V1);}\n",
      "71     \n",
      "72         if (py_V1 == Py_None)\n",
      "73         {\n",
      "74             V1 = NULL;\n",
      "75         }\n",
      "76         else\n",
      "77         {\n",
      "78             \n",
      "79         assert(py_V1->ob_refcnt >= 2); // There should be at least one ref from the container object,\n",
      "80         // and one ref from the local scope.\n",
      "81 \n",
      "82         if (CudaNdarray_Check(py_V1))\n",
      "83         {\n",
      "84             //fprintf(stderr, \"c_extract CNDA object w refcnt %p %i\\n\", py_V1, (py_V1->ob_refcnt));\n",
      "85             V1 = (CudaNdarray*)py_V1;\n",
      "86             //std::cerr << \"c_extract \" << V1 << '\\n';\n",
      "87         \n",
      "88 \n",
      "89                 if (V1->nd != 2)\n",
      "90                 {\n",
      "91                     PyErr_Format(PyExc_RuntimeError,\n",
      "92                                  \"c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 2\",\n",
      "93                                  V1->nd);\n",
      "94                     V1 = NULL;\n",
      "95                     {\n",
      "96         __failure = 2;\n",
      "97         if (!PyErr_Occurred()) {\n",
      "98             PyErr_SetString(PyExc_RuntimeError,\n",
      "99                 \"Unexpected error in an Op's C code. \"\n",
      "100                 \"No Python exception was set.\");\n",
      "101             }\n",
      "102         goto __label_2;};\n",
      "103                 }\n",
      "104                 //std::cerr << \"c_extract \" << V1 << \" nd check passed\\n\";\n",
      "105             \n",
      "106 \n",
      "107                 assert(V1);\n",
      "108                 Py_INCREF(py_V1);\n",
      "109             }\n",
      "110             else if (py_V1 == Py_None)\n",
      "111             {\n",
      "112                 PyErr_SetString(PyExc_TypeError,\n",
      "113                                 \"expected a CudaNdarray, not None\");\n",
      "114                 V1 = NULL;\n",
      "115                 {\n",
      "116         __failure = 2;\n",
      "117         if (!PyErr_Occurred()) {\n",
      "118             PyErr_SetString(PyExc_RuntimeError,\n",
      "119                 \"Unexpected error in an Op's C code. \"\n",
      "120                 \"No Python exception was set.\");\n",
      "121             }\n",
      "122         goto __label_2;};\n",
      "123             }\n",
      "124             else\n",
      "125             {\n",
      "126                 //fprintf(stderr, \"FAILING c_extract CNDA object w refcnt %p %i\\n\", py_V1, (py_V1->ob_refcnt));\n",
      "127                 PyErr_SetString(PyExc_TypeError, \"Argument not a CudaNdarray\");\n",
      "128                 V1 = NULL;\n",
      "129                 {\n",
      "130         __failure = 2;\n",
      "131         if (!PyErr_Occurred()) {\n",
      "132             PyErr_SetString(PyExc_RuntimeError,\n",
      "133                 \"Unexpected error in an Op's C code. \"\n",
      "134                 \"No Python exception was set.\");\n",
      "135             }\n",
      "136         goto __label_2;};\n",
      "137             }\n",
      "138             //std::cerr << \"c_extract done \" << V1 << '\\n';\n",
      "139             \n",
      "140 \n",
      "141         }\n",
      "142         \n",
      "143 {\n",
      "144 \n",
      "145     py_V3 = PyList_GET_ITEM(storage_V3, 0);\n",
      "146     {Py_XINCREF(py_V3);}\n",
      "147     \n",
      "148         assert(py_V3->ob_refcnt >= 2); // There should be at least one ref from the container object,\n",
      "149         // and one ref from the local scope.\n",
      "150 \n",
      "151         if (CudaNdarray_Check(py_V3))\n",
      "152         {\n",
      "153             //fprintf(stderr, \"c_extract CNDA object w refcnt %p %i\\n\", py_V3, (py_V3->ob_refcnt));\n",
      "154             V3 = (CudaNdarray*)py_V3;\n",
      "155             //std::cerr << \"c_extract \" << V3 << '\\n';\n",
      "156         \n",
      "157 \n",
      "158                 if (V3->nd != 2)\n",
      "159                 {\n",
      "160                     PyErr_Format(PyExc_RuntimeError,\n",
      "161                                  \"c_extract: Some CudaNdarray has rank %i, it was supposed to have rank 2\",\n",
      "162                                  V3->nd);\n",
      "163                     V3 = NULL;\n",
      "164                     {\n",
      "165         __failure = 4;\n",
      "166         if (!PyErr_Occurred()) {\n",
      "167             PyErr_SetString(PyExc_RuntimeError,\n",
      "168                 \"Unexpected error in an Op's C code. \"\n",
      "169                 \"No Python exception was set.\");\n",
      "170             }\n",
      "171         goto __label_4;};\n",
      "172                 }\n",
      "173                 //std::cerr << \"c_extract \" << V3 << \" nd check passed\\n\";\n",
      "174             \n",
      "175 \n",
      "176                 assert(V3);\n",
      "177                 Py_INCREF(py_V3);\n",
      "178             }\n",
      "179             else if (py_V3 == Py_None)\n",
      "180             {\n",
      "181                 PyErr_SetString(PyExc_TypeError,\n",
      "182                                 \"expected a CudaNdarray, not None\");\n",
      "183                 V3 = NULL;\n",
      "184                 {\n",
      "185         __failure = 4;\n",
      "186         if (!PyErr_Occurred()) {\n",
      "187             PyErr_SetString(PyExc_RuntimeError,\n",
      "188                 \"Unexpected error in an Op's C code. \"\n",
      "189                 \"No Python exception was set.\");\n",
      "190             }\n",
      "191         goto __label_4;};\n",
      "192             }\n",
      "193             else\n",
      "194             {\n",
      "195                 //fprintf(stderr, \"FAILING c_extract CNDA object w refcnt %p %i\\n\", py_V3, (py_V3->ob_refcnt));\n",
      "196                 PyErr_SetString(PyExc_TypeError, \"Argument not a CudaNdarray\");\n",
      "197                 V3 = NULL;\n",
      "198                 {\n",
      "199         __failure = 4;\n",
      "200         if (!PyErr_Occurred()) {\n",
      "201             PyErr_SetString(PyExc_RuntimeError,\n",
      "202                 \"Unexpected error in an Op's C code. \"\n",
      "203                 \"No Python exception was set.\");\n",
      "204             }\n",
      "205         goto __label_4;};\n",
      "206             }\n",
      "207             //std::cerr << \"c_extract done \" << V3 << '\\n';\n",
      "208             \n",
      "209 \n",
      "210 {\n",
      "211 // Op class GpuElemwise\n",
      "212 \n",
      "213         //std::cerr << \"C_CODE RoundHalfToEven START\\n\";\n",
      "214         //standard elemwise size checks\n",
      "215             \n",
      "216 \n",
      "217             int dims[2] = {1,1};\n",
      "218             \n",
      "219 \n",
      "220                 int broadcasts_V3[2] = {0, 0};\n",
      "221                 \n",
      "222 \n",
      "223         //std::cerr << \"C_CODE RoundHalfToEven checking input V3\\n\";\n",
      "224         if (2 != V3->nd)\n",
      "225         {\n",
      "226             PyErr_Format(PyExc_TypeError,\n",
      "227                          \"need 2 dims, not %i\", V3->nd);\n",
      "228             {\n",
      "229         __failure = 5;\n",
      "230         if (!PyErr_Occurred()) {\n",
      "231             PyErr_SetString(PyExc_RuntimeError,\n",
      "232                 \"Unexpected error in an Op's C code. \"\n",
      "233                 \"No Python exception was set.\");\n",
      "234             }\n",
      "235         goto __label_5;};\n",
      "236         }\n",
      "237         for (int i = 0; i< 2; ++i)\n",
      "238         {\n",
      "239             dims[i] = (dims[i] == 1) ? CudaNdarray_HOST_DIMS(V3)[i] : dims[i];\n",
      "240             if ((!(broadcasts_V3[i] &&\n",
      "241                  CudaNdarray_HOST_DIMS(V3)[i] == 1)) &&\n",
      "242                 (dims[i] != CudaNdarray_HOST_DIMS(V3)[i]))\n",
      "243             {\n",
      "244                 //std::cerr << \"C_CODE RoundHalfToEven checking input V3 failed\\n\";\n",
      "245                 PyErr_Format(PyExc_ValueError,\n",
      "246                              \"GpuElemwise. Input dimension mis-match. Input\"\n",
      "247                              \" 0 (indices start at 0) has shape[%i] == %i\"\n",
      "248                              \", but the output's size on that axis is %i.\",\n",
      "249                              i,\n",
      "250                              CudaNdarray_HOST_DIMS(V3)[i],\n",
      "251                              dims[i]\n",
      "252                             );\n",
      "253                 {\n",
      "254         __failure = 5;\n",
      "255         if (!PyErr_Occurred()) {\n",
      "256             PyErr_SetString(PyExc_RuntimeError,\n",
      "257                 \"Unexpected error in an Op's C code. \"\n",
      "258                 \"No Python exception was set.\");\n",
      "259             }\n",
      "260         goto __label_5;};\n",
      "261             }\n",
      "262         }\n",
      "263             \n",
      "264 \n",
      "265         Py_XDECREF(V1);\n",
      "266         V1 = V3;\n",
      "267         Py_INCREF(V1);\n",
      "268         for (int i = 0; (i< 2) && (V1); ++i) {\n",
      "269             if (dims[i] != CudaNdarray_HOST_DIMS(V1)[i])\n",
      "270             {\n",
      "271                 PyErr_Format(PyExc_ValueError,\n",
      "272                              \"GpuElemwise. Output dimension mis-match. Output\"\n",
      "273                              \" 0 (indices start at 0), working inplace\"\n",
      "274                              \" on input 0, has shape[%i] == %i\"\n",
      "275                              \", but the output's size on that axis is %i.\",\n",
      "276                              i,\n",
      "277                              CudaNdarray_HOST_DIMS(V1)[i],\n",
      "278                              dims[i]\n",
      "279                             );\n",
      "280                 Py_DECREF(V1);\n",
      "281                 V1 = NULL;\n",
      "282                 {\n",
      "283         __failure = 5;\n",
      "284         if (!PyErr_Occurred()) {\n",
      "285             PyErr_SetString(PyExc_RuntimeError,\n",
      "286                 \"Unexpected error in an Op's C code. \"\n",
      "287                 \"No Python exception was set.\");\n",
      "288             }\n",
      "289         goto __label_5;};\n",
      "290             }\n",
      "291         }\n",
      "292         //std::cerr << \"ELEMWISE NEW V1 nd\" << V1->nd << \"\\n\";\n",
      "293         //std::cerr << \"ELEMWISE NEW V1 data\" << V1->devdata << \"\\n\";\n",
      "294         \n",
      "295 \n",
      "296         {\n",
      "297             //new block so that failure gotos don't skip over variable initialization\n",
      "298             //std::cerr << \"calling callkernel\\n\";\n",
      "299             if (callkernel_node_3a084fd032db206a67ca8121a24aa32e_0(1, 0, dims\n",
      "300             \n",
      "301 \n",
      "302                         , CudaNdarray_DEV_DATA(V3), CudaNdarray_HOST_STRIDES(V3)\n",
      "303             \n",
      "304 \n",
      "305                         , CudaNdarray_DEV_DATA(V1), CudaNdarray_HOST_STRIDES(V1)\n",
      "306             \n",
      "307 \n",
      "308                         ))\n",
      "309             {\n",
      "310                  // error\n",
      "311             \n",
      "312 \n",
      "313                 Py_DECREF(V1);\n",
      "314                 V1 = NULL;\n",
      "315                 \n",
      "316 \n",
      "317                 {\n",
      "318         __failure = 5;\n",
      "319         if (!PyErr_Occurred()) {\n",
      "320             PyErr_SetString(PyExc_RuntimeError,\n",
      "321                 \"Unexpected error in an Op's C code. \"\n",
      "322                 \"No Python exception was set.\");\n",
      "323             }\n",
      "324         goto __label_5;};\n",
      "325             }\n",
      "326             else // no error\n",
      "327             {\n",
      "328             }\n",
      "329         }\n",
      "330         //std::cerr << \"C_CODE RoundHalfToEven END\\n\";\n",
      "331         \n",
      "332 __label_5:\n",
      "333 \n",
      "334 double __DUMMY_5;\n",
      "335 \n",
      "336 }\n",
      "337 __label_4:\n",
      "338 \n",
      "339         //std::cerr << \"cleanup \" << py_V3 << \" \" << V3 << \"\\n\";\n",
      "340         //fprintf(stderr, \"c_cleanup CNDA py_object w refcnt %p %i\\n\", py_V3, (py_V3->ob_refcnt));\n",
      "341         if (V3)\n",
      "342         {\n",
      "343             //fprintf(stderr, \"c_cleanup CNDA cn_object w refcnt %p %i\\n\", V3, (V3->ob_refcnt));\n",
      "344             Py_XDECREF(V3);\n",
      "345         }\n",
      "346         //std::cerr << \"cleanup done\" << py_V3 << \"\\n\";\n",
      "347         \n",
      "348     {Py_XDECREF(py_V3);}\n",
      "349     \n",
      "350 double __DUMMY_4;\n",
      "351 \n",
      "352 }\n",
      "353 __label_2:\n",
      "354 \n",
      "355     if (!__failure) {\n",
      "356       \n",
      "357         //std::cerr << \"sync\\n\";\n",
      "358         if (NULL == V1) {\n",
      "359             // failure: sync None to storage\n",
      "360             Py_XDECREF(py_V1);\n",
      "361             py_V1 = Py_None;\n",
      "362             Py_INCREF(py_V1);\n",
      "363         }\n",
      "364         else\n",
      "365         {\n",
      "366             if (py_V1 != (PyObject*)V1)\n",
      "367             {\n",
      "368                 Py_XDECREF(py_V1);\n",
      "369                 py_V1 = (PyObject*)V1;\n",
      "370                 Py_INCREF(py_V1);\n",
      "371             }\n",
      "372             assert(py_V1->ob_refcnt);\n",
      "373         }\n",
      "374         \n",
      "375       PyObject* old = PyList_GET_ITEM(storage_V1, 0);\n",
      "376       {Py_XINCREF(py_V1);}\n",
      "377       PyList_SET_ITEM(storage_V1, 0, py_V1);\n",
      "378       {Py_XDECREF(old);}\n",
      "379     }\n",
      "380     \n",
      "381         //std::cerr << \"cleanup \" << py_V1 << \" \" << V1 << \"\\n\";\n",
      "382         //fprintf(stderr, \"c_cleanup CNDA py_object w refcnt %p %i\\n\", py_V1, (py_V1->ob_refcnt));\n",
      "383         if (V1)\n",
      "384         {\n",
      "385             //fprintf(stderr, \"c_cleanup CNDA cn_object w refcnt %p %i\\n\", V1, (V1->ob_refcnt));\n",
      "386             Py_XDECREF(V1);\n",
      "387         }\n",
      "388         //std::cerr << \"cleanup done\" << py_V1 << \"\\n\";\n",
      "389         \n",
      "390     {Py_XDECREF(py_V1);}\n",
      "391     \n",
      "392 double __DUMMY_2;\n",
      "393 \n",
      "394 }\n",
      "395 \n",
      "396             \n",
      "397         if (__failure) {\n",
      "398             // When there is a failure, this code puts the exception\n",
      "399             // in __ERROR.\n",
      "400             PyObject* err_type = NULL;\n",
      "401             PyObject* err_msg = NULL;\n",
      "402             PyObject* err_traceback = NULL;\n",
      "403             PyErr_Fetch(&err_type, &err_msg, &err_traceback);\n",
      "404             if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}\n",
      "405             if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}\n",
      "406             if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}\n",
      "407             PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);\n",
      "408             PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);\n",
      "409             PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);\n",
      "410             PyList_SET_ITEM(__ERROR, 0, err_type);\n",
      "411             PyList_SET_ITEM(__ERROR, 1, err_msg);\n",
      "412             PyList_SET_ITEM(__ERROR, 2, err_traceback);\n",
      "413             {Py_XDECREF(old_err_type);}\n",
      "414             {Py_XDECREF(old_err_msg);}\n",
      "415             {Py_XDECREF(old_err_traceback);}\n",
      "416         }\n",
      "417         // The failure code is returned to index what code block failed.\n",
      "418         return __failure;\n",
      "419         \n",
      "420         }\n",
      "421     };\n",
      "422     }\n",
      "423     \n",
      "424 \n",
      "425         static int __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e_executor(__struct_compiled_op_3a084fd032db206a67ca8121a24aa32e* self) {\n",
      "426             return self->run();\n",
      "427         }\n",
      "428 \n",
      "429         static void __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e_destructor(void* executor, void* self) {\n",
      "430             delete ((__struct_compiled_op_3a084fd032db206a67ca8121a24aa32e*)self);\n",
      "431         }\n",
      "432         \n",
      "433 //////////////////////\n",
      "434 ////  Functions\n",
      "435 //////////////////////\n",
      "436 static PyObject * instantiate(PyObject * self, PyObject *argtuple) {\n",
      "437   assert(PyTuple_Check(argtuple));\n",
      "438   if (3 != PyTuple_Size(argtuple)){ \n",
      "439      PyErr_Format(PyExc_TypeError, \"Wrong number of arguments, expected 3, got %i\", (int)PyTuple_Size(argtuple));\n",
      "440      return NULL;\n",
      "441   }\n",
      "442   __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e* struct_ptr = new __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e();\n",
      "443   if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2) ) != 0) {\n",
      "444     delete struct_ptr;\n",
      "445     return NULL;\n",
      "446   }\n",
      "447   PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_3a084fd032db206a67ca8121a24aa32e_executor), struct_ptr, __struct_compiled_op_3a084fd032db206a67ca8121a24aa32e_destructor);\n",
      "448   return thunk; }\n",
      "449 \n",
      "450 //////////////////////\n",
      "451 ////  Module init\n",
      "452 //////////////////////\n",
      "453 static PyMethodDef MyMethods[] = {\n",
      "454 \t{\"instantiate\", instantiate, METH_VARARGS, \"undocumented\"} ,\n",
      "455 \t{NULL, NULL, 0, NULL}\n",
      "456 };\n",
      "457 PyMODINIT_FUNC init3a084fd032db206a67ca8121a24aa32e(void){\n",
      "458    (void) Py_InitModule(\"3a084fd032db206a67ca8121a24aa32e\", MyMethods);\n",
      "459 }\n",
      "460 \n",
      "===============================\n",
      "In file included from /home/ubuntu/anaconda2/include/python2.7/Python.h:8:0,\n",
      "                 from mod.cu:1:\n",
      "/home/ubuntu/anaconda2/include/python2.7/pyconfig.h:1193:0: warning: \"_POSIX_C_SOURCE\" redefined\n",
      " #define _POSIX_C_SOURCE 200112L\n",
      " ^\n",
      "In file included from /usr/local/cuda/include/host_config.h:173:0,\n",
      "                 from /usr/local/cuda/include/cuda_runtime.h:78,\n",
      "                 from <command-line>:0:\n",
      "/usr/include/features.h:228:0: note: this is the location of the previous definition\n",
      " # define _POSIX_C_SOURCE 200809L\n",
      " ^\n",
      "In file included from /home/ubuntu/anaconda2/include/python2.7/Python.h:8:0,\n",
      "                 from mod.cu:1:\n",
      "/home/ubuntu/anaconda2/include/python2.7/pyconfig.h:1215:0: warning: \"_XOPEN_SOURCE\" redefined\n",
      " #define _XOPEN_SOURCE 600\n",
      " ^\n",
      "In file included from /usr/local/cuda/include/host_config.h:173:0,\n",
      "                 from /usr/local/cuda/include/cuda_runtime.h:78,\n",
      "                 from <command-line>:0:\n",
      "/usr/include/features.h:169:0: note: this is the location of the previous definition\n",
      " # define _XOPEN_SOURCE 700\n",
      " ^\n",
      "mod.cu(299): error: identifier \"callkernel_node_3a084fd032db206a67ca8121a24aa32e_0\" is undefined\n",
      "1 error detected in the compilation of \"/tmp/tmpxft_00001427_00000000-9_mod.cpp1.ii\".\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "['nvcc', '-shared', '-O3', '--maxrregcount=32', '-arch=sm_37', '-m64', '-Xcompiler', '-fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray', '-I/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray', '-I/usr/local/cuda/include', '-I/home/ubuntu/anaconda2/lib/python2.7/site-packages/numpy/core/include', '-I/home/ubuntu/anaconda2/include/python2.7', '-I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof', '-I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda', '-o', '/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/tmpJHC8ya/3a084fd032db206a67ca8121a24aa32e.so', 'mod.cu', '-L/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray', '-L/home/ubuntu/anaconda2/lib', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython2.7']\n"
     ]
    },
    {
     "ename": "Exception",
     "evalue": "('The following error happened while compiling the node', GpuElemwise{RoundHalfToEven}[(0, 0)](GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)].0), '\\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --maxrregcount=32 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -I/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -I/usr/local/cuda/include -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda2/include/python2.7 -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda -o /home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/tmpJHC8ya/3a084fd032db206a67ca8121a24aa32e.so mod.cu -L/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -L/home/ubuntu/anaconda2/lib -lcudart -lcublas -lcuda_ndarray -lpython2.7', '[GpuElemwise{RoundHalfToEven}[(0, 0)](<CudaNdarrayType(float32, matrix)>)]')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m--------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m        Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-13-039aaae01435>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Fit the model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mY\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m150\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverbose\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/models.pyc\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)\u001b[0m\n\u001b[1;32m    958\u001b[0m                               \u001b[0minitial_epoch\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0minitial_epoch\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    959\u001b[0m                               \u001b[0msteps_per_epoch\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msteps_per_epoch\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 960\u001b[0;31m                               validation_steps=validation_steps)\n\u001b[0m\u001b[1;32m    961\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    962\u001b[0m     def evaluate(self, x, y, batch_size=32, verbose=1,\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)\u001b[0m\n\u001b[1;32m   1625\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1626\u001b[0m             \u001b[0mins\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0msample_weights\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1627\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_train_function\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1628\u001b[0m         \u001b[0mf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain_function\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1629\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc\u001b[0m in \u001b[0;36m_make_train_function\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    995\u001b[0m                                                  \u001b[0mupdates\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mupdates\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    996\u001b[0m                                                  \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'train_function'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 997\u001b[0;31m                                                  **self._function_kwargs)\n\u001b[0m\u001b[1;32m    998\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    999\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_make_test_function\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.pyc\u001b[0m in \u001b[0;36mfunction\u001b[0;34m(inputs, outputs, updates, **kwargs)\u001b[0m\n\u001b[1;32m   1230\u001b[0m                 \u001b[0mmsg\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'Invalid argument \"%s\" passed to K.function with Theano backend'\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mkey\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1231\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1232\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mFunction\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minputs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moutputs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mupdates\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mupdates\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1233\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1234\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.pyc\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, inputs, outputs, updates, name, **kwargs)\u001b[0m\n\u001b[1;32m   1216\u001b[0m                                         \u001b[0mon_unused_input\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'ignore'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1217\u001b[0m                                         \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1218\u001b[0;31m                                         **kwargs)\n\u001b[0m\u001b[1;32m   1219\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1220\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/compile/function.pyc\u001b[0m in \u001b[0;36mfunction\u001b[0;34m(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)\u001b[0m\n\u001b[1;32m    318\u001b[0m                    \u001b[0mon_unused_input\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mon_unused_input\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    319\u001b[0m                    \u001b[0mprofile\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mprofile\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 320\u001b[0;31m                    output_keys=output_keys)\n\u001b[0m\u001b[1;32m    321\u001b[0m     \u001b[0;31m# We need to add the flag check_aliased inputs if we have any mutable or\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    322\u001b[0m     \u001b[0;31m# borrowed used defined inputs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.pyc\u001b[0m in \u001b[0;36mpfunc\u001b[0;34m(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)\u001b[0m\n\u001b[1;32m    477\u001b[0m                          \u001b[0maccept_inplace\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0maccept_inplace\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    478\u001b[0m                          \u001b[0mprofile\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mprofile\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mon_unused_input\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mon_unused_input\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 479\u001b[0;31m                          output_keys=output_keys)\n\u001b[0m\u001b[1;32m    480\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    481\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.pyc\u001b[0m in \u001b[0;36morig_function\u001b[0;34m(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)\u001b[0m\n\u001b[1;32m   1775\u001b[0m                    \u001b[0mon_unused_input\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mon_unused_input\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1776\u001b[0m                    \u001b[0moutput_keys\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0moutput_keys\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1777\u001b[0;31m             defaults)\n\u001b[0m\u001b[1;32m   1778\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1779\u001b[0m     \u001b[0mt2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.pyc\u001b[0m in \u001b[0;36mcreate\u001b[0;34m(self, input_storage, trustme, storage_map)\u001b[0m\n\u001b[1;32m   1639\u001b[0m             \u001b[0mtheano\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtraceback\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlimit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1640\u001b[0m             _fn, _i, _o = self.linker.make_thunk(\n\u001b[0;32m-> 1641\u001b[0;31m                 input_storage=input_storage_lists, storage_map=storage_map)\n\u001b[0m\u001b[1;32m   1642\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1643\u001b[0m             \u001b[0mtheano\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtraceback\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlimit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlimit_orig\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/link.pyc\u001b[0m in \u001b[0;36mmake_thunk\u001b[0;34m(self, input_storage, output_storage, storage_map)\u001b[0m\n\u001b[1;32m    688\u001b[0m         return self.make_all(input_storage=input_storage,\n\u001b[1;32m    689\u001b[0m                              \u001b[0moutput_storage\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0moutput_storage\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 690\u001b[0;31m                              storage_map=storage_map)[:3]\n\u001b[0m\u001b[1;32m    691\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    692\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mmake_all\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minput_storage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moutput_storage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/vm.pyc\u001b[0m in \u001b[0;36mmake_all\u001b[0;34m(self, profiler, input_storage, output_storage, storage_map)\u001b[0m\n\u001b[1;32m   1001\u001b[0m                                                  \u001b[0mstorage_map\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1002\u001b[0m                                                  \u001b[0mcompute_map\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1003\u001b[0;31m                                                  no_recycling))\n\u001b[0m\u001b[1;32m   1004\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mthunks\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'lazy'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1005\u001b[0m                     \u001b[0;31m# We don't want all ops maker to think about lazy Ops.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.pyc\u001b[0m in \u001b[0;36mmake_thunk\u001b[0;34m(self, node, storage_map, compute_map, no_recycling)\u001b[0m\n\u001b[1;32m    254\u001b[0m                 enable_cuda=False)\n\u001b[1;32m    255\u001b[0m         return super(GpuOp, self).make_thunk(node, storage_map,\n\u001b[0;32m--> 256\u001b[0;31m                                              compute_map, no_recycling)\n\u001b[0m\u001b[1;32m    257\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    258\u001b[0m theano.compile.debugmode.default_make_thunk.append(\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/op.pyc\u001b[0m in \u001b[0;36mmake_thunk\u001b[0;34m(self, node, storage_map, compute_map, no_recycling)\u001b[0m\n\u001b[1;32m    968\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    969\u001b[0m                 return self.make_c_thunk(node, storage_map, compute_map,\n\u001b[0;32m--> 970\u001b[0;31m                                          no_recycling)\n\u001b[0m\u001b[1;32m    971\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mNotImplementedError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mutils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mMethodNotDefined\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    972\u001b[0m                 \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Falling back on perform'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/op.pyc\u001b[0m in \u001b[0;36mmake_c_thunk\u001b[0;34m(self, node, storage_map, compute_map, no_recycling)\u001b[0m\n\u001b[1;32m    877\u001b[0m         \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Trying CLinker.make_thunk'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    878\u001b[0m         outputs = cl.make_thunk(input_storage=node_input_storage,\n\u001b[0;32m--> 879\u001b[0;31m                                 output_storage=node_output_storage)\n\u001b[0m\u001b[1;32m    880\u001b[0m         \u001b[0mfill_storage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnode_input_filters\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnode_output_filters\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0moutputs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    881\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/cc.pyc\u001b[0m in \u001b[0;36mmake_thunk\u001b[0;34m(self, input_storage, output_storage, storage_map, keep_lock)\u001b[0m\n\u001b[1;32m   1198\u001b[0m         cthunk, in_storage, out_storage, error_storage = self.__compile__(\n\u001b[1;32m   1199\u001b[0m             \u001b[0minput_storage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moutput_storage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstorage_map\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1200\u001b[0;31m             keep_lock=keep_lock)\n\u001b[0m\u001b[1;32m   1201\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1202\u001b[0m         \u001b[0mres\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_CThunk\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcthunk\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minit_tasks\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtasks\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror_storage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/cc.pyc\u001b[0m in \u001b[0;36m__compile__\u001b[0;34m(self, input_storage, output_storage, storage_map, keep_lock)\u001b[0m\n\u001b[1;32m   1141\u001b[0m                                     \u001b[0moutput_storage\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1142\u001b[0m                                     \u001b[0mstorage_map\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1143\u001b[0;31m                                     keep_lock=keep_lock)\n\u001b[0m\u001b[1;32m   1144\u001b[0m         return (thunk,\n\u001b[1;32m   1145\u001b[0m                 [link.Container(input, storage) for input, storage in\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/cc.pyc\u001b[0m in \u001b[0;36mcthunk_factory\u001b[0;34m(self, error_storage, in_storage, out_storage, storage_map, keep_lock)\u001b[0m\n\u001b[1;32m   1593\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1594\u001b[0m             module = get_module_cache().module_from_key(\n\u001b[0;32m-> 1595\u001b[0;31m                 key=key, lnk=self, keep_lock=keep_lock)\n\u001b[0m\u001b[1;32m   1596\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1597\u001b[0m         \u001b[0mvars\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minputs\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutputs\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0morphans\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.pyc\u001b[0m in \u001b[0;36mmodule_from_key\u001b[0;34m(self, key, lnk, keep_lock)\u001b[0m\n\u001b[1;32m   1140\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1141\u001b[0m                 \u001b[0mlocation\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdlimport_workdir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdirname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1142\u001b[0;31m                 \u001b[0mmodule\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlnk\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompile_cmodule\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlocation\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1143\u001b[0m                 \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodule\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__file__\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1144\u001b[0m                 \u001b[0;32massert\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstartswith\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlocation\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof/cc.pyc\u001b[0m in \u001b[0;36mcompile_cmodule\u001b[0;34m(self, location)\u001b[0m\n\u001b[1;32m   1504\u001b[0m                 \u001b[0mlib_dirs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlib_dirs\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1505\u001b[0m                 \u001b[0mlibs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlibs\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1506\u001b[0;31m                 preargs=preargs)\n\u001b[0m\u001b[1;32m   1507\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1508\u001b[0m             \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0margs\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfgraph\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.pyc\u001b[0m in \u001b[0;36mcompile_str\u001b[0;34m(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, rpaths, py_module, hide_symbols)\u001b[0m\n\u001b[1;32m    397\u001b[0m             \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcmd\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    398\u001b[0m             raise Exception('nvcc return status', p.returncode,\n\u001b[0;32m--> 399\u001b[0;31m                             'for cmd', ' '.join(cmd))\n\u001b[0m\u001b[1;32m    400\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcmodule\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompilation_warning\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mnvcc_stdout\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    401\u001b[0m             \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnvcc_stdout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mException\u001b[0m: ('The following error happened while compiling the node', GpuElemwise{RoundHalfToEven}[(0, 0)](GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)].0), '\\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --maxrregcount=32 -arch=sm_37 -m64 -Xcompiler -fno-math-errno,-Wno-unused-label,-Wno-unused-variable,-Wno-write-strings,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -I/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -I/usr/local/cuda/include -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda2/include/python2.7 -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/gof -I/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda -o /home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/tmpJHC8ya/3a084fd032db206a67ca8121a24aa32e.so mod.cu -L/home/ubuntu/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/cuda_ndarray -L/home/ubuntu/anaconda2/lib -lcudart -lcublas -lcuda_ndarray -lpython2.7', '[GpuElemwise{RoundHalfToEven}[(0, 0)](<CudaNdarrayType(float32, matrix)>)]')"
     ]
    }
   ],
   "source": [
    "# Fit the model\n",
    "model.fit(X, Y, epochs=150, batch_size=10, verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# evaluate the model\n",
    "scores = model.evaluate(X, Y)\n",
    "print(\"\\n%s: %.2f%%\" % (model.metrics_names[1], scores[1]*100))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda root]",
   "language": "python",
   "name": "conda-root-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
